//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIAssignment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIAssignment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons, my Government&apos;s legislative programme will focus on economic growth, justice and constitutional reform.
        ///My Ministers&apos; first priority will be to reduce the deficit and restore economic stability.
        ///Legislation will be introduced to reduce burdens on business by repealing unnecessary legislation and to limit state inspection of businesses.
        ///My Government will introduce legislation to reform competition law to promote enterprise and fair markets.
        ///My Government wil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Coalition9thMay2012 {
            get {
                return ResourceManager.GetString("Coalition9thMay2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons, 
        ///The Duke of Edinburgh and I look forward to receiving the state visit of His Highness the Amir of Kuwait in May and His Excellency the President of Finland in October next year. 
        ///The Duke of Edinburgh and I look forward to our state visit to South Africa in March. We also look forward to our visit to New Zealand and to the Commonwealth heads of government meeting there in November next year. 
        ///My Government attach the highest importance to national security.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conservative16thNov1994 {
            get {
                return ResourceManager.GetString("Conservative16thNov1994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons, my Government will legislate in the interests of everyone in our country. They will adopt a one-nation approach, helping working people get on, supporting aspiration, giving new opportunities to the most disadvantaged and bringing different parts of our country together.
        ///My Government will continue with their long-term plan to provide economic stability and security at every stage of life. They will continue the work of bringing the public finances under contro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conservative27thMay2015 {
            get {
                return ResourceManager.GetString("Conservative27thMay2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons 
        ///My Government will maintain its key commitment to economic stability and growth. 
        ///This will enable my Government to continue to deliver reform of the public services and continue to focus on greater opportunity and social justice, enhanced security and protection and constitutional reform. 
        ///Delivering a world class education system that enables individuals to achieve their full potential remains my Government&apos;s main priority for Britain&apos;s future success. Educ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Labour26thNov2003 {
            get {
                return ResourceManager.GetString("Labour26thNov2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons, my Government will take forward policies to respond to the rising aspirations of the people of the United Kingdom; to ensure security for all; and to entrust more power to Parliament and the people.
        ///My Government’s programme will meet people’s aspirations for better education, housing, healthcare and children’s services, and for a cleaner environment.
        ///My Government is committed to raising educational standards and giving everyone the chance to reach their full [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Labour6thNov2007 {
            get {
                return ResourceManager.GetString("Labour6thNov2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///above
        ///across
        ///after
        ///again
        ///against
        ///all
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///among
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyone
        ///anything
        ///anywhere
        ///are
        ///area
        ///areas
        ///around
        ///as
        ///ask
        ///asked
        ///asking
        ///asks
        ///at
        ///away
        ///b
        ///back
        ///backed
        ///backing
        ///backs
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///been
        ///before
        ///began
        ///behind
        ///being
        ///beings
        ///best
        ///better
        ///between
        ///big
        ///both
        ///but
        ///by
        ///c
        ///came
        ///can
        ///cannot
        ///case
        ///cases
        ///certain
        ///certainly
        ///clear
        ///clearly
        ///come
        ///could
        ///d
        ///did
        ///differ
        ///different
        ///di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stopwords {
            get {
                return ResourceManager.GetString("stopwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons, my Government’s legislative programme will continue to deliver on its long-term plan to build a stronger economy and a fairer society.
        ///To strengthen the economy and provide stability and security, my Ministers will continue to reduce the country’s deficit, helping to ensure that mortgage and interest rates remain low.
        ///An updated Charter for Budget Responsibility will be brought forward to ensure that future Governments spend taxpayers’ money responsibly.
        ///My G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons, 
        ///The Duke of Edinburgh and I look forward to receiving the state visit of His Excellency the President of France and of His Excellency the President of South Africa next year. We also look forward to our state visits to Poland and the Czech Republic in March and to Thailand in October next year. 
        ///National security remains of the highest importance to my Government. They will continue to support the North Atlantic Treaty Organisation and to promote Britain&apos;s wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lords and Members of the House of Commons,
        ///My Government&apos;s central objectives are economic stability, and investment and reform in public services, leading to a more prosperous and inclusive society. To this end, my Government will continue to secure low inflation and sound public finances.
        ///My Government&apos;s main priorities for the forthcoming Session will be reform in education, health, crime and welfare.
        ///My Government will introduce legislation to reform education. An education Bill will be introduced [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
    }
}
